# .github/workflows/ci.yml

name: Basic CI for Streamlit App

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest pandas scikit-learn

      - name: Run unit and integration tests
        run: |
          # Go to the app directory to run the tests
          cd app
          # The test file is in the root, so go up one level to find it
          pytest ../test_my_expenses.py -v
          
  docker-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test Docker container
        run: |
          docker build -t expenses-app ./app
          docker run -d --name test-container -p 8501:8501 expenses-app
          sleep 10
          docker logs test-container
          docker stop test-container
          docker rm test-container