# .github/workflows/ci.yml

name: Student Expenses App CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run tests
        run: |
          # Add the 'app' directory to the Python path
          export PYTHONPATH=./app:$PYTHONPATH
          pytest test_my_expenses.py

  docker-build-and-run:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run Docker container
        run: |
          docker build -t expenses-app ./app
          docker run -d --name test-container -p 8501:8501 expenses-app
          sleep 15
          docker logs test-container
          docker stop test-container
          docker rm test-container